### ISSUE TITLE
Crash on title screen or character selection screen with Dalamud 6.0.9.0

### ISSUE THREAD

**Issue by haojunsui** [akira0245/DalamudCNAdapter#1]
After release of Dalamud 6.0.9.0, game crashes with this plugin installed. Crash always happenes after a few seconds loading the game (mostly I will be in title screen or character selection screen). Tried to see if there's any crash report in dalamud.log file but there's nothing interesting. The last few lines from log show that dalamud loaded a few addons.

Example:
```
......
2021-11-01 18:25:47.264 -07:00 [INF] [PLUGINM] Loading plugin FPS Plugin
2021-11-01 18:25:47.286 -07:00 [INF] [LOCALPLUGIN] Loading FPSPlugin.dll
2021-11-01 18:25:47.291 -07:00 [INF] [LOCALPLUGIN] Finished loading FPSPlugin.dll
2021-11-01 18:25:47.291 -07:00 [INF] [PLUGINM] Loading plugin GatherBuddy
2021-11-01 18:25:47.343 -07:00 [INF] [LOCALPLUGIN] Loading GatherBuddy.dll<EOF>
```

I have roughly 40 plugins installed. After disabling this plugin, dalamud was initialized successfully. Here's the event log from Windows:
```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  - <System>
      <Provider Name="Application Error" /> 
      <EventID Qualifiers="0">1000</EventID> 
      <Version>0</Version> 
      <Level>2</Level> 
      <Task>100</Task> 
      <Opcode>0</Opcode> 
      <Keywords>0x80000000000000</Keywords> 
      <TimeCreated SystemTime="2021-11-02T01:35:53.9571445Z" /> 
      <EventRecordID>3754</EventRecordID> 
      <Correlation /> 
      <Execution ProcessID="0" ThreadID="0" /> 
      <Channel>Application</Channel> 
      <Computer>DESKTOP-9UT2L28</Computer> 
      <Security /> 
    </System>
  - <EventData>
      <Data>ffxiv_dx11.exe</Data> 
      <Data>1.0.0.0</Data> 
      <Data>611aabe1</Data> 
      <Data>ntdll.dll</Data> 
      <Data>10.0.19041.1288</Data> 
      <Data>a280d1d6</Data> 
      <Data>c0000374</Data> 
      <Data>00000000000ff199</Data> 
      <Data>7198</Data> 
      <Data>01d7cf89eaf6fd7a</Data> 
      <Data>D:\SquareEnix\FINAL FANTASY XIV - A Realm Reborn\game\ffxiv_dx11.exe</Data> 
      <Data>C:\WINDOWS\SYSTEM32\ntdll.dll</Data> 
      <Data>13bebf62-da8b-4606-a3dc-bede611935f1</Data> 
      <Data /> 
      <Data /> 
    </EventData>
  </Event>
```

I mostly use this plugin for radar and other useful plugin from you. Luckily, those plugins work perfectly fine without this adapter; however, it would still be nice to enable this adapter to get rid of annoying "=" character.

**Comment by akira0245** [comment]
This plugin is only replacing dalamud's default font `NotoSansCJKjp` to `NotoSansCJKsc`, this function it self should not cause a crush.
But ImGui's font atlas has a size limitation, if you have too many plugins building too many fonts(ping plugin builds 1, delvUI is building 3 or 4 afaik), the game will crush.
You could try disable some of them to see if the problem persists. 
Since this plugin only replace dalamud's font, it won't fix the `=` characters in game's chat/dialog. to fix these 
 you could try install this mod which replaces game's font texture.

**Comment by akira0245** [comment]
https://github.com/akira0245/DalamudCNAdapter/blob/master/resources/ChnFontRange.ttmp2

**Comment by haojunsui** [comment]
That crash is most likely coming from ImGUI's font building. I really wish that gets resolved by dalamud's team someday.

"=" character I was referring to is the one in Radar plugin setting page in Dalamud. But it's nice to hear we have a mod to replace in-game font texture.
