### ISSUE TITLE
和 Chat2/XIVAuras等插件冲突

### ISSUE THREAD

**Issue by beckyeeky** [akira0245/DalamudCNAdapter#3]
DalamudFontReplacer和一些比较新的，涉及游戏内文本的插件冲突，比如Chat2/XIVAuras等，导致游戏直接闪退。
请问有没有简单的workaround避免？

**Comment by akira0245** [comment]
现在只确定如果有插件build了太多字体导致imgui的font atlas超过某个大小会导致闪退
可能反射替换一下卫月buildfont的方法而不是替换build好的font能解决吧 但是不太简单的样子

**Comment by beckyeeky** [comment]
谢谢回复，目前先避免同时启用好了。
